package com.coderjoe.atlas

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.yaml.snakeyaml.Yaml
import java.io.File

/**
 * Checks that every model a config names actually exists.
 *
 * CraftEngine only reports these as warnings at server start, and a block whose model is missing
 * renders untextured rather than failing loudly, so the two mistakes this catches are easy to ship:
 * an item pointing at a model nothing produces, and a generated model whose `path` collides with
 * the `parent` it inherits from - which silently overwrites the parent's geometry.
 */
class ConfigModelReferenceTest {
    private companion object {
        val CONFIG_DIR = File("src/main/resources/atlas/configuration")
        val MODEL_DIR = File("src/main/resources/atlas/resourcepack/assets/minecraft/models/block/custom")
        val ITEM_MODEL_DIR = File("src/main/resources/atlas/resourcepack/assets/minecraft/models/item/custom")
        val ITEM_TEXTURE_DIR = File("src/main/resources/atlas/resourcepack/assets/minecraft/textures/item/custom")
        val BLOCK_TEXTURE_DIR = File("src/main/resources/atlas/resourcepack/assets/minecraft/textures/block/custom")

        /** Keys of an item model definition that hold further model definitions. */
        val NESTED_MODEL_KEYS = setOf("cases", "fallback", "model", "on_true", "on_false")
    }

    private fun configs(): List<Map<String, Any?>> =
        CONFIG_DIR.listFiles { f -> f.extension == "yml" }!!
            .map { Yaml().load<Map<String, Any?>>(it.readText()) }

    @Suppress("UNCHECKED_CAST")
    private fun blocks(): List<Pair<String, Map<String, Any?>>> =
        configs().flatMap { doc ->
            doc.entries
                .filter { it.key.startsWith("items") }
                .flatMap { (_, items) ->
                    (items as? Map<String, Any?> ?: emptyMap()).map { (id, cfg) ->
                        id to (cfg as Map<String, Any?>)
                    }
                }
        }

    @Suppress("UNCHECKED_CAST")
    private fun modelBlocks(cfg: Map<String, Any?>): List<Map<String, Any?>> {
        val block =
            (cfg["behavior"] as? Map<String, Any?>)?.get("block") as? Map<String, Any?>
                ?: return emptyList()
        val states = block["states"] as? Map<String, Any?>
        val appearances = (states?.get("appearances") as? Map<String, Any?>)?.values.orEmpty()
        val single = listOfNotNull(block["state"] as? Map<String, Any?>)
        return (appearances.mapNotNull { it as? Map<String, Any?> } + single)
            .mapNotNull { it["model"] as? Map<String, Any?> }
    }

    private fun leaf(reference: String) = reference.substringAfterLast("/")

    /**
     * Flattens an item's `model` into every concrete model it can resolve to.
     *
     * A plain string is one model. A model definition may instead branch - a `minecraft:select` on
     * the display context, say - so each branch has to be checked, not just the first one found.
     */
    @Suppress("UNCHECKED_CAST")
    private fun itemModels(node: Any?): List<Map<String, Any?>> =
        when (node) {
            is String -> listOf(mapOf("path" to node))
            is List<*> -> node.flatMap(::itemModels)
            is Map<*, *> -> {
                val map = node as Map<String, Any?>
                val self = if (map["path"] is String) listOf(map) else emptyList()
                self + NESTED_MODEL_KEYS.flatMap { itemModels(map[it]) }
            }
            else -> emptyList()
        }

    @Test
    fun `every item model reference exists or is generated by the block`() {
        val unresolved = mutableListOf<String>()

        for ((id, cfg) in blocks()) {
            for (model in itemModels(cfg["model"])) {
                val reference = model["path"] as String
                val name = leaf(reference)
                val directory = if (reference.contains("/item/")) ITEM_MODEL_DIR else MODEL_DIR
                if (File(directory, "$name.json").exists()) continue
                // A model carrying its own `generation` block is written by CraftEngine at pack build.
                if (model["generation"] != null) continue

                val generated = modelBlocks(cfg).mapNotNull { it["path"] as? String }.map(::leaf)
                if (name !in generated) unresolved += "$id -> $reference"
            }
        }

        assertTrue(unresolved.isEmpty(), "item models with no model file and nothing generating them: $unresolved")
    }

    @Test
    fun `every generated item icon texture exists`() {
        val missing = mutableListOf<String>()

        for ((id, cfg) in blocks()) {
            for (model in itemModels(cfg["model"])) {
                @Suppress("UNCHECKED_CAST")
                val textures =
                    (model["generation"] as? Map<String, Any?>)?.get("textures") as? Map<String, Any?>
                        ?: continue
                for (reference in textures.values.filterIsInstance<String>()) {
                    if (!reference.startsWith("minecraft:item/custom/")) continue
                    if (!File(ITEM_TEXTURE_DIR, "${leaf(reference)}.png").exists()) missing += "$id -> $reference"
                }
            }
        }

        assertTrue(missing.isEmpty(), "item icon textures named by a config but not shipped: $missing")
    }

    /** Every `generation.textures` map in a config, wherever it is nested. */
    @Suppress("UNCHECKED_CAST")
    private fun textureMaps(node: Any?): List<Map<String, Any?>> =
        when (node) {
            is List<*> -> node.flatMap(::textureMaps)
            is Map<*, *> -> {
                val map = node as Map<String, Any?>
                val own =
                    (map["generation"] as? Map<String, Any?>)
                        ?.get("textures") as? Map<String, Any?>
                listOfNotNull(own) + map.values.flatMap(::textureMaps)
            }
            else -> emptyList()
        }

    @Test
    fun `every texture a config names actually exists`() {
        val missing = mutableListOf<String>()

        for (config in CONFIG_DIR.listFiles { f -> f.extension == "yml" }!!) {
            val doc = Yaml().load<Map<String, Any?>>(config.readText())
            for (textures in textureMaps(doc)) {
                for ((slot, reference) in textures) {
                    val name = reference as? String ?: continue
                    val directory =
                        when {
                            reference.startsWith("minecraft:item/custom/") -> ITEM_TEXTURE_DIR
                            reference.startsWith("minecraft:block/custom/") -> BLOCK_TEXTURE_DIR
                            // anything outside our own namespaces is vanilla and always present
                            else -> continue
                        }
                    if (!File(directory, "${leaf(name)}.png").exists()) {
                        missing += "${config.name}: $slot -> $reference"
                    }
                }
            }
        }

        assertTrue(missing.isEmpty(), "textures named by a config but not shipped: $missing")
    }

    @Test
    fun `no generated model overwrites the parent it inherits from`() {
        val collisions = mutableListOf<String>()

        for ((id, cfg) in blocks()) {
            for (model in modelBlocks(cfg)) {
                val path = model["path"] as? String ?: continue

                @Suppress("UNCHECKED_CAST")
                val parent = (model["generation"] as? Map<String, Any?>)?.get("parent") as? String ?: continue
                if (path == parent) collisions += "$id -> $path"
            }
        }

        assertTrue(collisions.isEmpty(), "generated model path equals its parent, clobbering the geometry: $collisions")
    }

    @Test
    fun `every generation parent has a model file`() {
        val missing = mutableListOf<String>()

        for ((id, cfg) in blocks()) {
            for (model in modelBlocks(cfg)) {
                @Suppress("UNCHECKED_CAST")
                val parent = (model["generation"] as? Map<String, Any?>)?.get("parent") as? String ?: continue
                if (parent.startsWith("minecraft:block/custom/") && !File(MODEL_DIR, "${leaf(parent)}.json").exists()) {
                    missing += "$id -> $parent"
                }
            }
        }

        assertTrue(missing.isEmpty(), "generation parents with no model file: $missing")
    }
}
